#redis 配置192.168.96.140:6379
db:
  password:
  addr:   192.168.1.107:6379
  user: 
  database: 1

#httpServer
http:
  addr:   0.0.0.0:8081

#mysql
mysql:
  addr: 192.168.1.107:3306
  user: root
  password: root
  database: video

#upload file address
uploadfile:
  path: file