#redis 配置192.168.96.140:6379
db:
  password:
  addr:   127.0.0.1:6379
  user: 
  database: 1

#httpServer
http:
  addr:   127.0.0.1:8010

#mysql
mysql:
  addr: 127.0.0.1:3306
  user: root
  password: icsoc
  database: video